installedESLint: true
env:
    browser: true
    es6: true
rules:
    no-use-before-define: 0
    no-trailing-spaces: 1
    no-multi-spaces: 0
    no-unused-vars: 0
    one-var: 0
    arrow-parens: 0
    key-spacing: 0
    require-jsdoc: 0
    no-throw-literal: 0
    no-multiple-empty-lines: 0
    max-len: ["error", 100]
    semi: 1
